ignore:
  - "tests/"
  - "psi4/driver/qcdb/"
  - "psi4/share/"
  - "psi4/src/psi4/libtrans/"
  - "psi4/src/psi4/transqt2/"
  - "psi4/src/psi4/lib3index/"
  - "psi4/src/psi4/libfilesystem/"
  - "psi4/src/psi4/libiwl/"
  - "psi4/src/psi4/libthce/"
  - "psi4/src/psi4/libfunctional/"
